"""
Neural network core
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['ActivationFunction', 'LossFunction', 'Matrix', 'Net']
class ActivationFunction:
    """
    Members:
    
      NO
    
      RELU
    
      SOFTMAX
    
      SIGMOID
    """
    NO: typing.ClassVar[ActivationFunction]  # value = <ActivationFunction.NO: 3>
    RELU: typing.ClassVar[ActivationFunction]  # value = <ActivationFunction.RELU: 0>
    SIGMOID: typing.ClassVar[ActivationFunction]  # value = <ActivationFunction.SIGMOID: 1>
    SOFTMAX: typing.ClassVar[ActivationFunction]  # value = <ActivationFunction.SOFTMAX: 2>
    __members__: typing.ClassVar[dict[str, ActivationFunction]]  # value = {'NO': <ActivationFunction.NO: 3>, 'RELU': <ActivationFunction.RELU: 0>, 'SOFTMAX': <ActivationFunction.SOFTMAX: 2>, 'SIGMOID': <ActivationFunction.SIGMOID: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class LossFunction:
    """
    Members:
    
      MSE
    
      CROSSENROPY
    """
    CROSSENROPY: typing.ClassVar[LossFunction]  # value = <LossFunction.CROSSENROPY: 1>
    MSE: typing.ClassVar[LossFunction]  # value = <LossFunction.MSE: 0>
    __members__: typing.ClassVar[dict[str, LossFunction]]  # value = {'MSE': <LossFunction.MSE: 0>, 'CROSSENROPY': <LossFunction.CROSSENROPY: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class Matrix:
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def identity(size: typing.SupportsInt | typing.SupportsIndex) -> Matrix:
        ...
    @staticmethod
    def ones(height: typing.SupportsInt | typing.SupportsIndex, width: typing.SupportsInt | typing.SupportsIndex) -> Matrix:
        ...
    @staticmethod
    def zeros(height: typing.SupportsInt | typing.SupportsIndex, width: typing.SupportsInt | typing.SupportsIndex) -> Matrix:
        ...
    def __add__(self, other: Matrix) -> Matrix:
        ...
    def __eq__(self, other: Matrix) -> bool:
        ...
    def __iadd__(self, other: Matrix) -> Matrix:
        ...
    @typing.overload
    def __imul__(self, other: Matrix) -> Matrix:
        ...
    @typing.overload
    def __imul__(self, other: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    @typing.overload
    def __init__(self, height: typing.SupportsInt | typing.SupportsIndex, width: typing.SupportsInt | typing.SupportsIndex, default_values: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, values: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]]) -> None:
        ...
    @typing.overload
    def __init__(self, input: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    def __isub__(self, other: Matrix) -> Matrix:
        ...
    @typing.overload
    def __mul__(self, other: Matrix) -> Matrix:
        ...
    @typing.overload
    def __mul__(self, other: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    def __rmul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Matrix:
        ...
    def __sub__(self, other: Matrix) -> Matrix:
        ...
    def element_wise_multiplication(self, other: Matrix) -> Matrix:
        ...
    def load_from_txt(self, file_name: str) -> None:
        ...
    def transpose(self) -> Matrix:
        ...
    @property
    def m(self) -> int:
        ...
    @property
    def matrix_values(self) -> list[list[float]]:
        ...
    @property
    def n(self) -> int:
        ...
class Net:
    def BatchTrain(self, arg0: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]], arg1: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]], arg2: typing.SupportsInt | typing.SupportsIndex, arg3: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def CalculateLoss(self, arg0: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex], arg1: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> float:
        ...
    def DumpToBinary(self, arg0: str) -> None:
        ...
    def FillByRandomValues(self) -> None:
        ...
    def FillByZeros(self) -> None:
        ...
    def ForwardPass(self, arg0: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> list[float]:
        ...
    def ReadFromBinary(self, arg0: str) -> None:
        ...
    def SetLayersAcivation(self, arg0: collections.abc.Sequence[ActivationFunction]) -> None:
        ...
    def SetLoss(self, arg0: LossFunction) -> None:
        ...
    def Train(self, arg0: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]], arg1: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]], arg2: typing.SupportsInt | typing.SupportsIndex, arg3: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def learning_step(self) -> float:
        ...
    @learning_step.setter
    def learning_step(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
