"""
Neural network core
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['Net']
class Net:
    def CalculateLoss(self, arg0: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex], arg1: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> float:
        ...
    def DumpToBinary(self, arg0: str) -> None:
        ...
    def FillByRandomValues(self) -> None:
        ...
    def FillByZeros(self) -> None:
        ...
    def ForwardPass(self, arg0: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> list[float]:
        ...
    def ReadFromBinary(self, arg0: str) -> None:
        ...
    def SetActivationRelu(self) -> None:
        ...
    def SetActivationSigmoid(self) -> None:
        ...
    def SetLossMSE(self) -> None:
        ...
    def Train(self, arg0: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]], arg1: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]], arg2: typing.SupportsInt | typing.SupportsIndex, arg3: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def TrainingForwardPass(self, arg0: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> list[float]:
        ...
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def learning_step(self) -> float:
        ...
    @learning_step.setter
    def learning_step(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
